/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto.Vistas;

/**
 *
 * @author marco
 */
public class Vista_JuegoUS extends javax.swing.JDialog {

    /**
     * Creates new form Vista_JuegoUS
     */
    public Vista_JuegoUS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_question = new javax.swing.JLabel();
        jr_answer1 = new javax.swing.JRadioButton();
        jr_answer2 = new javax.swing.JRadioButton();
        jr_answer3 = new javax.swing.JRadioButton();
        jr_answer4 = new javax.swing.JRadioButton();
        jb_respond = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jl_question.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_question.setText("jLabel1");

        jr_answer1.setText("jRadioButton1");

        jr_answer2.setText("jRadioButton2");

        jr_answer3.setText("jRadioButton3");

        jr_answer4.setText("jRadioButton4");

        jb_respond.setText("Responder");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jr_answer4)
                            .addComponent(jr_answer3)
                            .addComponent(jr_answer2)
                            .addComponent(jr_answer1)
                            .addComponent(jl_question)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jb_respond)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jl_question)
                .addGap(18, 18, 18)
                .addComponent(jr_answer1)
                .addGap(18, 18, 18)
                .addComponent(jr_answer2)
                .addGap(18, 18, 18)
                .addComponent(jr_answer3)
                .addGap(18, 18, 18)
                .addComponent(jr_answer4)
                .addGap(18, 18, 18)
                .addComponent(jb_respond)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_JuegoUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_JuegoUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_JuegoUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_JuegoUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vista_JuegoUS dialog = new Vista_JuegoUS(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_respond;
    public javax.swing.JLabel jl_question;
    public javax.swing.JRadioButton jr_answer1;
    public javax.swing.JRadioButton jr_answer2;
    public javax.swing.JRadioButton jr_answer3;
    public javax.swing.JRadioButton jr_answer4;
    // End of variables declaration//GEN-END:variables
}
